name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install frontend dependencies
        run: npm install
        working-directory: frontendReact

      - name: Run frontend tests
        run: npm test
        working-directory: frontendReact

  backend:
    runs-on: ubuntu-22.04  # Changed to Ubuntu 22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js for Backend
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl1.1

      - name: Configure MongoDB for testing
        run: |
          echo "module.exports = { 
            mongodbMemoryServerOptions: { 
              binary: { 
                version: '5.0.22',
                skipMD5: true
              },
              instance: {
                dbName: 'jest'
              },
              autoStart: false
            }
          };" > jest-mongodb-config.js
        working-directory: Backend

      - name: Install backend dependencies
        run: npm install
        working-directory: Backend

      - name: Run backend tests
        run: npm test
        working-directory: Backend